FROM node:22-alpine

WORKDIR /app

RUN npm install -g tsx nodemon

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["nodemon", "--exec", "tsx", "src/server.ts", "--watch", "src"]
